try {
 throw 1;
 } catch(e) {
 log('caught', e);
 }